# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake

on:
  workflow_dispatch: # lets you run a build from the UI
  push:
  #pull_request:

# When pushing new commits, cancel any running builds on that branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash

jobs:
  build-clap:
    name: clap ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        include:
          - name: Linux
            os: ubuntu-24.04
          - name: macOS
            os: macos-14
            #extra-flags: -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" # https://github.com/libsdl-org/setup-sdl/issues/33
            extra-flags: -DCMAKE_OSX_ARCHITECTURES="x86_64"
          - name: Windows
            # https://github.com/actions/runner-images/issues/10980
            os: windows-2025

    steps:
      - name: Set up Linux deps
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libsdl2-dev
          version: 1.0
      - uses: libsdl-org/setup-sdl@main
        if: runner.os != 'Linux' # 500 fetch error for some reason :(
        id: sdl
        with:
          install-linux-dependencies: true
          version: 3-latest
          version-sdl-image: 3-latest

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} "${{github.workspace}}/clap" ${{matrix.extra-flags}}

      - name: Build
        run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}}

  #modify-plugin-version:
  #  name: Modify plugin version
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: actions/cache@v4
  #      id: plugin-version-cache
  #      with:
  #        path: plugin.json
  #        key: ${{ github.sha }}-${{ github.run_id }}
  #    - run: |
  #        gitrev=`git rev-parse --short HEAD`
  #        pluginversion=`jq -r '.version' plugin.json`
  #        echo "Set plugin version from $pluginversion to $pluginversion-$gitrev"
  #        cat <<< `jq --arg VERSION "$pluginversion-$gitrev" '.version=$VERSION' plugin.json` > plugin.json
  #      # only modify plugin version if no tag was created
  #      if: "! startsWith(github.ref, 'refs/tags/v')"

  build-vcvrack:
    name: vcvrack ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        include:
          - name: Linux
            os: ubuntu-22.04
            generator: Unix Makefiles
          - name: macOS x86_64
            os: macos-14
            extra-flags: -DCMAKE_OSX_ARCHITECTURES="x86_64"
            generator: Unix Makefiles
          - name: macOS arm64
            os: macos-14
            extra-flags: -DCMAKE_OSX_ARCHITECTURES="arm64"
            generator: Unix Makefiles
          - name: Windows
            os: windows-latest
            generator: MinGW Makefiles
    steps:
      - name: Set up MinGW
        if: runner.os == 'Windows'
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
          static: 0

      - name: Set up Linux deps
        if: runner.os == 'Linux'
        # https://github.com/VCVRack/rack-plugin-toolchain/blob/v2/Makefile#L268
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ca-certificates git build-essential autoconf automake bison flex gawk libtool-bin libncurses5-dev unzip zip jq libgl-dev libglu-dev git wget curl cmake nasm xz-utils file python3 libxml2-dev libssl-dev texinfo help2man libz-dev rsync xxd perl coreutils zstd markdown libarchive-tools
          version: 1.0

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "${{matrix.generator}}" "${{github.workspace}}/vcvrack" ${{matrix.extra-flags}}

      - name: Build
        run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}}
        
      - name: install
        run: cmake --install "${{github.workspace}}/build" --prefix "${{github.workspace}}/build/dist"

      - name: Package
        uses: actions/upload-artifact@v4
        with:
          name: KitsBlips-VCVRack-${{ matrix.name }}
          path: "${{github.workspace}}/build/dist" 

  build-daisy:
    name: daisy ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        include:
          - name: Linux
            os: ubuntu-22.04
    steps:
      - name: Setup arm-none-eabi-gcc
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: "9-2019-q4"

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} "${{github.workspace}}/daisy"

      - name: Build
        run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}}

      - name: install
        run: cmake --install "${{github.workspace}}/build" --prefix "${{github.workspace}}/build/dist"

      - name: Package
        uses: actions/upload-artifact@v4
        with:
          name: KitsBlips-Daisy
          path: "${{github.workspace}}/build/dist" 
